### ISSUE TITLE
Train$，PredictRate$，PredictValue$ path no find entrance in uweb

### ISSUE THREAD

**Issue by shilicqupt** [Tencent/Metis#44]
- Train$，PredictRate$，PredictValue$ path no find entrance in uweb, how to use them in the web
- when to train model, is streaming predict value or predict rate then is anomaly then we record it

**Comment by zr9558** [comment]
> * Train$，PredictRate$，PredictValue$ path no find entrance in uweb, how to use them in the web
> * when to train model, is streaming predict value or predict rate then is anomaly then we record it

1. the entrance of predict value and rate is not in UWeb. It is in server, please use api in server to detect anomaly points，https://github.com/Tencent/Metis/blob/master/docs/api_userguide.md
2. after trained a model, we need to use stream of time series to detect value or rate. If they are anomaly points, then we record them; otherwise, we do not need to record them, because normal cases are much more than abnormal cases.
